### ISSUE TITLE
Changing topic configuration generates a replace instead of an update

### ISSUE THREAD

**Issue by userkci** [confluentinc/terraform-provider-confluentcloud#11]
After having created a topic:

```hcl
resource "confluentcloud_kafka_topic" "foobar" {
  kafka_cluster = var.kafka_cluster_id
  topic_name = "foobar"
  partitions_count = 1
  http_endpoint = var.kafka_http_endpoint
  config = {
    "retention.ms" = "600000"
  }
 credentials {
    key = var.kafka_api_key
    secret = var.kafka_api_secret
 }
```

When changing `retention.ms`, `terraform plan` shows it will delete/recreate the topic instead of modifying in place:

```console
Terraform will perform the following actions:

  # confluentcloud_kafka_topic.foobar must be replaced
-/+ resource "confluentcloud_kafka_topic" "foobar" {
      ~ config           = { # forces replacement
          ~ "retention.ms" = "600000" -> "6000000"
        }
      ~ id               = "<cluster id>/foobar" -> (known after apply)
        # (4 unchanged attributes hidden)

        credentials {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I did not verify, but I'd suspect it doesn't matter which configuration parameter you change. This is certainly undesirable in most, if not all, cases of changing topic configuration parameters. I also observed that changing `partitions_count` will similarly trigger a replace instead of update. I could see arguments either way for this.

The [alternative Terraform provider for managing Kafka topics and ACLs](https://github.com/Mongey/terraform-provider-kafka) an issues an in-place update in the same situations.

**Comment by AnishJS** [comment]
This seems critical and a basic requirement, when would it be available please?

**Comment by gof-ctm** [comment]
Am waiting for a resolve because if I change Topic name then it gets replaced not updated.

**Comment by moonsub-kim** [comment]
Does v0.4.0 resolve this? @linouk23

**Comment by linouk23** [comment]
@moonsub-kim unfortunately it doesn't.

**Comment by linouk23** [comment]
@moonsub-kim @gof-ctm @AnishJS @userkci @vpoyraz @jmborsani

I've got a quick question regarding this issue: will it be helpful to introduce topic config updates without allowing a user to delete a topic config at all (but supporting value updates`"retention.ms" = "600000" -> "6000000"` / adding new topic configs)? Please react either 👍 or 👎 .

**Comment by pbarsotti-glovo** [comment]
Also deletion is not a sync operation, so many times the creation fails with an error "Error: 400 Bad Request: Topic 'topic_name' is marked for deletion." since the provider is not waiting for the finalization before trying to recreate it.

**Comment by linouk23** [comment]
@pbarsotti-glovo interesting, you mean like topic deletion?

**Comment by linouk23** [comment]
Check out our most recent release of the [TF Provider for Confluent Cloud `v0.5.0`](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#050-march-9-2022) where we fixed the issue!

cc @pbarsotti-glovo @moonsub-kim @gof-ctm @AnishJS @userkci @vpoyraz @jmborsani @EaglelJoe
