### ISSUE TITLE
Topic and ACL resources store Kafka API credentials in state file

### ISSUE THREAD

**Issue by userkci** [confluentinc/terraform-provider-confluentcloud#12]
After creating topics and ACLs with the provider, the Kafka API credentials used are stored in the state file. This is, I suppose, done to allow deletion of the resources (otherwise, you have no way of knowing the credentials since the resource is not present in the inputs).

While sensitive data is [allowed in the state file](https://www.terraform.io/docs/language/state/sensitive-data.html), in this case it is certainly unexpected. At the least, this ought to be documented. Alternatively, if managing topics and ACLs did not require the Kafka API key or if topics and ACLs were managed by a second type of provider (holding the credentials), then credentials might not be required in the state.

**Comment by linouk23** [comment]
@userkci check out [the docs](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project) for our new `0.2.0` version where we [documented](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md) this issue.

![image](https://user-images.githubusercontent.com/5459870/140556928-7aba7d73-0464-4c9c-8487-d01de3ec2f3d.png)


Thank you for catching the issue!

**Comment by KBalderson** [comment]
Hey @linouk23!

I don't think a warning in the docs actually solves OPs problem.

When I run `terraform state pull`, I can see my Kafka API Keys (not confluent keys) in the state file. It's not the provider config that's the problem, it's the state that is stored for the ACLs and topics.

The provider is able to be provisioned with environment variables, but the `confluentcloud_kafka_topic` and `confluentcloud_kafka_acl` dump the secrets into the state file regardless of the configuration.

Maybe a second set of environment variables can be introduced, or... if you _really_ want to maintain the ability to act on two clusters, maybe the `credentials` configuration in these resources could be updated to allow the user to specify the environment variables from which to read these values.

**Comment by linouk23** [comment]
@KBalderson you're right, that specific doc note might be a bit confusing and it corresponds to both Kafka & Cloud API Keys.

The idea here is to follow Terraform official [docs](https://www.terraform.io/language/state/sensitive-data#recommendations) about _Sensitive Data in State_:

> If you manage any sensitive data with Terraform (like database passwords, user passwords, or private keys), treat the state itself as sensitive data.

Speaking about
> Maybe a second set of environment variables can be introduced

That's a great idea but we did see a feedback that it's not super convenient to set env vars to even for 2+ clusters (let alone 50+).

> maybe the credentials configuration in these resources could be updated to allow the user to specify the environment variables from which to read these values.

I think TF Provider allows users to update `credentials` block.

**Comment by linouk23** [comment]
Here's the screenshot I wanted to posted in one my previous messages: 
![image](https://user-images.githubusercontent.com/5459870/156699494-7ea138c4-ff34-48e6-a284-4c1bb9d050a6.png)
