### ISSUE TITLE
set acl to topic

### ISSUE THREAD

**Issue by vickrame** [confluentinc/terraform-provider-confluentcloud#14]
when i use the script in the "sample projet", i have this error `The argument "host" is required, but no definition was found.`

But in the doc, i don't see this parameter 
`resource "confluentcloud_kafka_acl" "describe-orders" {
  kafka_cluster = confluentcloud_kafka_cluster.test-basic-cluster.id
  resource_type = "TOPIC"
  resource_name = confluentcloud_kafka_topic.orders.topic_name
  pattern_type = "LITERAL"
  principal = "User:${var.service_account_int_id}"
  operation = "DESCRIBE"
  permission = "ALLOW"
  http_endpoint = confluentcloud_kafka_cluster.test-basic-cluster.http_endpoint
  credentials {
    key = var.kafka_api_key
    secret = var.kafka_api_secret
  }
}`

It is a mistake ?

**Comment by njokic** [comment]
@vickrame please make sure you're using the latest `0.2.0` version of TF Provider by using the following snippet in your `main.tf` file:
```
terraform {
  required_providers {
    confluentcloud = {
      source  = "confluentinc/confluentcloud"
      version = "0.2.0"
    }
  }
}
```

If the problem persists, please add `host = "*"` to your resource attribute (e.g., see the [old docs](https://registry.terraform.io/providers/confluentinc/confluentcloud/0.1.0/docs/guides/sample-project) for `0.1.0` version), i.e.:
```
resource "confluentcloud_kafka_acl" "describe-orders" {
  kafka_cluster = confluentcloud_kafka_cluster.test-basic-cluster.id
  resource_type = "TOPIC"
  resource_name = confluentcloud_kafka_topic.orders.topic_name
  pattern_type = "LITERAL"
  principal = "User:${var.service_account_int_id}"
  host = "*"
  operation = "DESCRIBE"
  permission = "ALLOW"
  http_endpoint = confluentcloud_kafka_cluster.test-basic-cluster.http_endpoint
  credentials {
    key = var.kafka_api_key
    secret = var.kafka_api_secret
  }
}
```

**Comment by linouk23** [comment]
@vickrame could you please let me know whether the fix provided by @njokic (it looks reasonable to me) worked for you?
