### ISSUE TITLE
Error: 429 Too Many Requests

### ISSUE THREAD

**Issue by RabahZeineddine** [confluentinc/terraform-provider-confluentcloud#15]
I am receiving this error on `terraform plan`. 

 I do have more than 35 topics
 
│ Error: 429 Too Many Requests
│ 
│   with confluentcloud_kafka_topic.topics["<topic_name>"],
│   on main.tf line 17, in resource "confluentcloud_kafka_topic" "topics":
│   17: resource "confluentcloud_kafka_topic" "topics" {
│ 
╵

**Comment by linouk23** [comment]
@RabahZeineddine thanks for opening an issue!

Could you try to run
```
terraform plan -parallelism=1
```
instead of
```
terraform plan
```

**Comment by RabahZeineddine** [comment]
limiting the concurrent operations to 1 using 
`terraform plan -parallelism=1`
it worked!

**Comment by linouk23** [comment]
I'm glad to hear that! FWIW you can do the same when running `terraform apply` -> `terraform apply -parallelism=1`.

**Comment by fdmota** [comment]
It works but it feels like a workaround... Any plans to change this?

**Comment by linouk23** [comment]
👋 @RabahZeineddine please check out our most recent [0.4.0 release](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#040-january-28-2022) where we fixed the issue!
