### ISSUE TITLE
HTTP 403 when creating a service account

### ISSUE THREAD

**Issue by svetozar02** [confluentinc/terraform-provider-confluentcloud#16]
Hi, 

I've created a global access API key at https://confluent.cloud/environments/XXX/clusters/XXX/api-keys.  I was able to create a topic which means that my confluent cloud api key / provider is setup properly. 

However, I'm getting a HTTP 403 error when trying to create a service account:

```
confluentcloud_service_account.core-service-sa: Creating...
╷
│ Error: 403 Forbidden
│ 
│   with confluentcloud_service_account.core-service-sa,
│   on main.tf line 48, in resource "confluentcloud_service_account" "core-service-sa":
│   48: resource "confluentcloud_service_account" "core-service-sa" {
│ 
╵
```

Any thoughts?

**Comment by linouk23** [comment]
Hi @svetozar02, 

Could you [check](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project#prerequisites) that your org has been flagged for Early Access?
![image](https://user-images.githubusercontent.com/5459870/143042110-1fdd5bc3-7eef-470a-bb6f-a0ae30f00632.png)

Let me know if that helps.

**Comment by svetozar02** [comment]
That makes sense. I'll request access.
