### ISSUE TITLE
How to create an api key for a service account? 

### ISSUE THREAD

**Issue by svetozar02** [confluentinc/terraform-provider-confluentcloud#17]
It seems we can create a service account by using https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/resources/confluentcloud_service_account. 
How do we create an api key for that account?

**Comment by linouk23** [comment]
`confluentcloud_api_key` resource is not available in the most recent `0.2.0` version (so creating an api key is not possible via terraform but you could use [CLI](https://docs.confluent.io/confluent-cli/current/command-reference/api-key/confluent_api-key_create.html) instead) but it's on our roadmap, stay tuned!

**Comment by AClarkie** [comment]
> 

Hey @linouk23 do you know when this feature will be delivered?

**Comment by linouk23** [comment]
I can't give you any exact timelines but hopefully it'll be included in one of our next releases.

**Comment by AClarkie** [comment]
Thanks for the quick response, I realise an exact time frame might be difficult to provide but could you give me a rough estimate e.g. Q1 2022?

The reason I ask is that we will roll our own solution if it's unlikely to be addressed in the next few months.

**Comment by linouk23** [comment]
> Thanks for the quick response, I realise an exact time frame might be difficult to provide but could you give me a rough estimate e.g. Q1 2022?

I see, I don't want to commit to anything but it's very likely that it's going to be addressed in the next 1-2 months.

**Comment by AClarkie** [comment]
> > Thanks for the quick response, I realise an exact time frame might be difficult to provide but could you give me a rough estimate e.g. Q1 2022?
> 
> I see, I don't want to commit to anything but it's very likely that it's going to be addressed in the next 1-2 months.

That's great thanks

**Comment by linouk23** [comment]
Not sure why I closed this issue 😕

**Comment by ConfluentSpencer** [comment]
Duplicate of this ask:
https://github.com/confluentinc/terraform-provider-confluentcloud/issues/4

**Comment by linouk23** [comment]
@svetozar02 @AClarkie, @marthjod we're very excited to let you know we've just published a new version of TF Provider that includes `api_key` resource among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).
