### ISSUE TITLE
username/password not supported in provider

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluentcloud#2]
The [examples](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/examples/provider/provider.tf) specify that username/password can be used in the provider.  However, in my case when I try the same
```
provider "confluentcloud" {
  username = var.api_key
  password = var.api_secret
}
```

I see the below error
```
Error: Unsupported argument
│ 
│   on providers.tf line 2, in provider "confluentcloud":
│    2:   username = var.api_key
│ 
│ An argument named "username" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on providers.tf line 3, in provider "confluentcloud":
│    3:   password = var.api_secret
│ 
│ An argument named "password" is not expected here.
```

Much appreciated.

**Comment by linouk23** [comment]
Thanks for both opening the issue and sharing the fix! 👏

You're right, one needs to use `api_key` instead of `username` and `api_secret` instead of `password`, e.g.:
```
$ cat variables.tf
variable "confluent_cloud_api_key" {
  type = string
  description = "Cloud API Key"
  sensitive = true
}

variable "confluent_cloud_api_secret" {
  type = string
  description = "Cloud API Secret"
  sensitive = true
}

$ cat terraform.tfvars
confluent_cloud_api_key="..."
confluent_cloud_api_secret="..."

$ cat main.tf
terraform {
  required_providers {
    confluentcloud = {
      source  = "confluentinc/confluentcloud"
      version = "0.1.0"
    }
  }
}

provider "confluentcloud" {
  api_key = var.confluent_cloud_api_key
  api_secret = var.confluent_cloud_api_secret
}

# Create the resources
...
```

We're going to fix it in our next release 👌

**Comment by linouk23** [comment]
@bluedog13 check out [the docs](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project) for our new `0.2.0` version where we [fixed](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md) that documentation bug.
![image](https://user-images.githubusercontent.com/5459870/140557832-d9045324-6251-4c93-8aed-9a32001f4ecd.png)
Thank you for catching the issue!
