### ISSUE TITLE
BUG: Credentials configuration block isn't being updated

### ISSUE THREAD

**Issue by venkatamutyala** [confluentinc/terraform-provider-confluentcloud#21]
Steps to recreate:
1) Create cluster specific API keys in Confluent Cloud Console.
2) Create a topic resource using the keys from #1: https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/resources/confluentcloud_kafka_topic
3) Remove API Keys (#1) in Confluent Cloud
4) Create new set of credentials (#1) and update the credentials block (#2)
5) Run a plan/apply and get a 401 error
6) Check the state file and you will see the old credentials that were removed

**Comment by linouk23** [comment]
Thanks for creating an issue @venkatamutyala, we'll try to address it on our next `0.3.0` release of TF Provider!

**Comment by linouk23** [comment]
@venkatamutyala 
FYI you can currently fix it by editing TF state manually to use your new Cluster API Key (until we release a new version of TF provider).

**Comment by linouk23** [comment]
@venkatamutyala please check out our recent `0.3.0` release that allows you to update `credentials` [block](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/resources/confluentcloud_kafka_acl):
![image](https://user-images.githubusercontent.com/5459870/149052249-eec276b2-0a4f-4735-bb3d-54b0fd9a1d33.png)
