### ISSUE TITLE
Error: 429 Too Many Requests

### ISSUE THREAD

**Issue by fdmota** [confluentinc/terraform-provider-confluentcloud#22]
I get the following errors:

```
│ Error: 429 Too Many Requests
│ 
│   with module.sentry_kafka_topics.confluentcloud_kafka_topic.kafka_topics["outcomes"],
│   on ../../../../../../modules/confluent-kafka-topics/main.tf line 1, in resource "confluentcloud_kafka_topic" "kafka_topics":
│    1: resource "confluentcloud_kafka_topic" "kafka_topics" {
```

with code that looks like this:

```
resource "confluentcloud_kafka_topic" "kafka_topics" {
  for_each = var.topics

  topic_name       = each.value.topic_name
  partitions_count = each.value.partitions_count
  config           = each.value.config

  kafka_cluster = var.cluster_info.cluster_id
  http_endpoint = var.cluster_info.http_endpoint
  credentials {
    key    = local.cluster_credentials.api
    secret = local.cluster_credentials.secret
  }
}
```

I temporarily resolved the issue by adding a sleep of 1 second between calls in the provider
```
func kafkaTopicRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
        log.Printf("[INFO] Kafka topic read2 for %s", d.Id())
        throttle() <-- Sleep 1s

        clusterId := extractClusterId(d)
        topicName := extractTopicName(d)
```

Is there a better solution?

**Comment by linouk23** [comment]
Thanks for opening an issue!

Could you try https://github.com/confluentinc/terraform-provider-confluentcloud/issues/15#issuecomment-972131964?

**Comment by fdmota** [comment]
It works but it feels like a workaround... Any plans to change this?

**Comment by linouk23** [comment]
We're anticipating a rate limit increase for a corresponding API as soon as TF providers goes into Preview / General Access from the current Early Access stage.

**Comment by linouk23** [comment]
@fdmota could you share more details about your fix with `throttle()`? It might be a good idea for us to implement something similar while waiting for a rate limit increase.

**Comment by fdmota** [comment]
it was nothing very fancy. I created a quick sleep of 1 second to experiment if it would work.
`func throttle () {
        time.Sleep(1 * time.Second)
        log.Printf("[INFO] Sleep Over.....")
}
`

**Comment by linouk23** [comment]
👋 @fdmota @vilmosnagy please check out our most recent [0.4.0 release](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#040-january-28-2022) where we fixed the issue!
