### ISSUE TITLE
can't create topics/acls for dedicated clusters

### ISSUE THREAD

**Issue by tatianameleshko** [confluentinc/terraform-provider-confluentcloud#23]
Having issues  when creating topics and ACLs on the dedicated cluster (PrivateLink). It works fine with basic clusters.  what can be the  cause of this issue - is  that dedicated clusters don't have REST endpoint enabled?

confluentcloud_kafka_topic.test: Creating...
│ Error: 404 Not Found
│   with confluentcloud_kafka_topic.test,
│   on test.tf line 17, in resource "confluentcloud_kafka_topic" "test":
│   17: resource "confluentcloud_kafka_topic" "test" {

**Comment by linouk23** [comment]
Thanks for creating an issue @tatianameleshko!

That's definitely a bit surprising to see since we did test topic creation for dedicated clusters _on public network_ but not for VPC peering, AWS Transit Gateway, AWS PrivateLink, and Azure PrivateLink yet.

Could you share any debug logs [with us](cflt-tf-access@confluent.io) and reference this issue such that our team will take a look at it?

**Comment by linouk23** [comment]
@tatianameleshko 

I followed up with our Networking team and I would like to confirm topic / ACLs creation only works for dedicated clusters on public network (i.e., not Private Link) at the moment.

We are aware of the issue and we're going to address it in our next releases.

**Comment by igwejk** [comment]
@linouk23 thanks for looking into this issue. Do you have a timeline for when the fix can be released?

**Comment by linouk23** [comment]
@igwejk can't promise anything but we're hoping to release it in Q2.

**Comment by bluedog13** [comment]
In the past (v0.3.0), I have been able to create topics and ACL's on basic kafka cluster.

**Comment by ConfluentSpencer** [comment]
Work to improve Topic and ACL Resources for Private Link clusters is underway.

**Comment by linouk23** [comment]
@igwejk, @tatianameleshko we're very excited to let you know we've just published a new version of TF Provider that includes a fix for this issue (adding PrivateLink support) among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

To be more specific, here's the example of a setup _Dedicated Kafka cluster on AWS that is accessible via PrivateLink connections with authorization using RBAC_: https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-aws-kafka-rbac
