### ISSUE TITLE
403 on terraform apply

### ISSUE THREAD

**Issue by rafaelleme** [confluentinc/terraform-provider-confluentcloud#24]
i can't create my environment or basic cluster, when I run terraform apply, it returns error 403 forbidden.

main.tf >>>

```
terraform {
  required_providers {
    confluentcloud = {
      source  = "confluentinc/confluentcloud"
      version = "0.2.0"
    }
  }
}

provider "confluentcloud" {}

resource "confluentcloud_environment" "test-env" {
  display_name = "Development"
}

resource "confluentcloud_kafka_cluster" "basic-cluster" {
  display_name = "basic_kafka_cluster"
  availability = "SINGLE_ZONE"
  cloud        = "AWS"
  region       = "sa-east-1"
  basic {}

  environment {
    id = confluentcloud_environment.test-env.id
  }
}
```
```
confluentcloud_environment.ccloud-environment: Creating...

Error: 403 Forbidden

  on main.tf line 1, in resource "confluentcloud_environment" "test-env:
   12: resource "confluentcloud_environment" "test-env" {

```

tf version 
```
terraform -v
Terraform v0.15.5
on linux_amd64
```

**Comment by atimush** [comment]
Hello, 
Same here. 403 :(

**Comment by linouk23** [comment]
@rafaelleme @atimush thanks for raising an issue!

Could you [check](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project#prerequisites) that your org has been flagged for Early Access?
![image](https://user-images.githubusercontent.com/5459870/143048201-6897186d-6294-494f-a40a-c2025f0893da.png)

Let me know if that helps.

**Comment by rafaelleme** [comment]
@linouk23 I confess that I missed this part, tks for the help, i will email to request access

**Comment by atimush** [comment]
Thank you, @linouk23. I've just requested it and will let u know the results when ready.

**Comment by linouk23** [comment]
To close the loop, I think @atimush resolved the access issue.
