### ISSUE TITLE
Deploying "Apache Kafka on Confluent Cloud"

### ISSUE THREAD

**Issue by mzehetho** [confluentinc/terraform-provider-confluentcloud#27]
Hello,

as far as I understand it, this Terraform Provider "only" connects to an existing Confluent Cloud instance, that was created manually previously. Wouldn't it be better to create the Cloud integration with this provider too?
https://azure.microsoft.com/en-us/blog/introducing-seamless-integration-between-microsoft-azure-and-confluent-cloud/

Maybe it would even be possible to forego the need of the api key and secret, by using a Service Principal or Managed Identitiy.

Am I missing something, or is this planned for the future?

Thanks for your help!

**Comment by linouk23** [comment]
Thanks for asking this question @mzehetho!

> as far as I understand it, this Terraform Provider "only" connects to an existing Confluent Cloud instance, that was created manually previously. 

I don't think this statement ⬆️ is correct. Please take a look at our [Sample Project](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project) tutorial that shows how one could create a bunch of resources on Confluent Cloud automatically via Terraform.
