### ISSUE TITLE
Use service account id instead of integer id for principal argument

### ISSUE THREAD

**Issue by cmaobeehive** [confluentinc/terraform-provider-confluentcloud#31]
Hi,
When creating the `confluentcloud_kafka_acl` resource I need to provide the `principal` argument which seems only accepting an "integer id" instead of, for example, `confluentcloud_service_account.id`.
Is there any plan to support `confluentcloud_service_account.id` in the future in order to be able to reference it directly by using `principal = "User:${confluentcloud_service_account.test-sa.id}"`? so that I don't need to create service account first and then manually retrieve the "integer id" which is also a hacky procedure imho as this id is not returned/documented anywhere when using REST API or Confluent CLI.

Cheers,

**Comment by linouk23** [comment]
Hi @cmaobeehive and thanks for opening an issue!

Your note is exactly right, and we're actively working on to address this limitation in our future releases of TF Provider for Confluent Cloud.

**Comment by linouk23** [comment]
@cmaobeehive starting from `0.4.0` [version](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#040-january-28-2022) TF Provider supports `principal = "User:sa-abc123"` so you don't need to look up corresponding int ID manually and can reference SA's ID:
```
principal     = "User:${confluentcloud_service_account.app-producer.id}"
```
