### ISSUE TITLE
Service account data source by display name

### ISSUE THREAD

**Issue by azsefi** [confluentinc/terraform-provider-confluentcloud#42]
Current service account data source does not make it possible to provide display name and get the id as output. It is frequently needed to get service account id to use for example in a topic acl. Is it possible to add that feature?

**Comment by linouk23** [comment]
Unfortunately that is currently not supported still underlying API requires Service Account ID for a [read](https://docs.confluent.io/cloud/current/api.html#operation/getIamV2ServiceAccount) request.

I'd probably recommend either use service account data source by [providing](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/data-sources/confluentcloud_service_account) its ID or use service account [resource](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/resources/confluentcloud_service_account).

**Comment by linouk23** [comment]
@azsefi given the fact there's a similar request #46 we might be able to add it in the following release.

**Comment by linouk23** [comment]
Check out our most recent release of the [TF Provider for Confluent Cloud `v0.5.0`](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#050-march-9-2022) where we fixed the issue!

cc @azsefi
