### ISSUE TITLE
Id check fails for old environments

### ISSUE THREAD

**Issue by azsefi** [confluentinc/terraform-provider-confluentcloud#43]
Because of the [check](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/a1758cfd64209dec64b3a099254ab5faf97c41b0/internal/provider/provider.go#L149) we can not use the terraform module with our existing environments. Old environment IDs do not start with "env-" prefix. Is there any special reason for that check? Can the check be relaxed to make it possible to use with older environments?

**Comment by linouk23** [comment]
Thanks for opening an issue @azsefi!

That's a great catch, we'll fix it in `0.5.0`!

**Comment by linouk23** [comment]
Check out our most recent release of the [TF Provider for Confluent Cloud `v0.5.0`](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#050-march-9-2022) where we fixed the issue!

cc @azsefi
