### ISSUE TITLE
creation of networks and dedicated clusters over the private link

### ISSUE THREAD

**Issue by tatianameleshko** [confluentinc/terraform-provider-confluentcloud#45]
Hello, When the functional to create networks and dedicated clusters over the private link will be available? Thank you

**Comment by linouk23** [comment]
Thanks for asking @tatianameleshko!

These resources should be available next quarter but I can’t promise anything.

**Comment by linouk23** [comment]
@tatianameleshko we're very excited to let you know we've just published a new version of TF Provider that includes `network` / `privatelink` / `peering` resources among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

To be more specific, here's the example of a setup _Dedicated Kafka cluster on AWS that is accessible via PrivateLink connections with authorization using RBAC_: https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-aws-kafka-rbac
