### ISSUE TITLE
Ability to get resources environments by name instead of just id.

### ISSUE THREAD

**Issue by AKrill91** [confluentinc/terraform-provider-confluentcloud#46]
It would be extremely helpful to be able to look up the id of an environment or cluster given its name. I could see this either being done using the existing data sources, or adding new plural forms of the existing data sources that return lists that can then be filtered on the caller side. An example of the latter in another provider would be the aws_eks_cluster and aws_eks_cluster**S** data sources in the aws provider.

**Comment by linouk23** [comment]
Created a separate issue #49 for clusters specifically.

**Comment by linouk23** [comment]
Check out our most recent release of the [TF Provider for Confluent Cloud `v0.5.0`](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#050-march-9-2022) where we fixed the issue!

cc @AKrill91 @atimush @raytung @matefarcas-recrd
