### ISSUE TITLE
Add confluentcloud_user data source

### ISSUE THREAD

**Issue by linouk23** [confluentinc/terraform-provider-confluentcloud#61]
### What
Add confluentcloud_user data source (see [User](https://docs.confluent.io/cloud/current/api.html#tag/Users-(iamv2)) on the Confluent Cloud API docs).

### How
We could start by looking at @dwimsey's amazing [PR](https://github.com/confluentinc/terraform-provider-confluentcloud/pull/60).

**Comment by linouk23** [comment]
We're very excited to let you know we've just published a new version of TF Provider that includes `user` data source among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

**Comment by adronamraju** [comment]
Hi @linouk23 , I noticed you added API keys to the official provider. is this for cloud, schema and cluster API keys? if so, does the cluster API key work on Dedicated Clusters on Private Link?

**Comment by linouk23** [comment]
@adronamraju you might take a look at `confluent_api_key` resource's [docs](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key) for all the details but to answer your specific question, as of now (`0.7.0` version) `confluent_api_key` resource supports both Cloud and Kafka API Keys (schema registry clusters / keys are not supported at the moment).

> if so, does the cluster API key work on Dedicated Clusters on Private Link?

They do! Moreover, you could use one of the prewritten e2e fully automated [configurations](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations) to simplify your deployment process (so you only need to fill in `terraform.tfvars` without writing any `.tf` configuration files from scratch):
* [dedicated-privatelink-aws-kafka-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-aws-kafka-rbac)
* [dedicated-privatelink-azure-kafka-rbac](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-azure-kafka-rbac)

Also you might find more instructions about running it (as well as a cool [demo](https://asciinema.org/a/491871)) by reading our updated [Sample Project](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project) guide.

Feel free to ping me here or create new [issues](https://github.com/confluentinc/terraform-provider-confluent/issues) if you run into any problems.
