### ISSUE TITLE
Add Kafka API key as a resource

### ISSUE THREAD

**Issue by JWDobken** [confluentinc/terraform-provider-confluentcloud#66]
I am missing the creation of an API key in the cluster environment. We are migrating from the unofficial provider: [Mongey/terraform-provider-confluentcloud](https://github.com/Mongey/terraform-provider-confluentcloud).

What I expect as input:

```tf
resource "confluentcloud_api_key" "api_key" {
  cluster_id     = confluentcloud_kafka_cluster.cluster.id
  environment_id = confluentcloud_environment.confluent_environment.id
  description    = "my API KEY for the ${confluentcloud_environment.confluent_environment.display_name} environment"
}
```

That outputs the key and secret as input for topics:

```tf
resource "confluentcloud_kafka_topic" "orders" {
  kafka_cluster      = confluentcloud_kafka_cluster.basic-cluster.id
   ...
  credentials {
    key    = confluentcloud_api_key.api_key.key
    secret = confluentcloud_api_key.api_key.secret
  }
}
```

**Comment by linouk23** [comment]
👋 @JWDobken thanks for opening an issue!

We're aware of this issue and it's been a pretty popular ask indeed: see #4, #17, #25.

The latest news is that we're targeting to release a new version of TF Provider (with `confluentcloud_api_key` resource) on April 28th 🤞

**Comment by JWDobken** [comment]
Thanks for your reply @linouk23

I'll close this issue and keep an eye on the other issues :)

**Comment by maheshbhole** [comment]
> 👋 @JWDobken thanks for opening an issue!
> 
> We're aware of this issue and it's been a pretty popular ask indeed: see #4, #17, #25.
> 
> The latest news is that we're targeting to release a new version of TF Provider (with `confluentcloud_api_key` resource) on April 28th 🤞 that will enable e2e provisioning of Confluent Cloud infrastructure in a single `terraform apply` run.

Hi,
 
When is next release for this provider , with confluentcloud_api_key as resource?

**Comment by muaaaz** [comment]
@linouk23 thanks for the feedback :)

**Comment by linouk23** [comment]
@muaaaz, @maheshbhole, @JWDobken we're very excited to let you know we've just published a new version of TF Provider that includes `api_key` resource among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).

**Comment by muaaaz** [comment]
@linouk23 thanks for the update this sounds really cool! However, it seems that there is an issue with the documentation website. After navigating to the [confluent_api_key](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key) resource page from the [sample-project](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project) page, I'm getting a "404 Page Not Found This documentation page doesn't exist for version 0.7.0 of the confluent provider."

**Comment by linouk23** [comment]
@muaaaz thanks for reporting it! I've opened https://github.com/confluentinc/terraform-provider-confluent/issues/10 where I'll publish the missing doc as a screenshot for now and then we'll update a provider.

**Comment by muaaaz** [comment]
@linouk23 awesome thank you very much for the quick response!

**Comment by linouk23** [comment]
update: the docs were updated and https://github.com/confluentinc/terraform-provider-confluent/issues/10 has been closed ✅
