### ISSUE TITLE
No ability to automate creation of cluster api-keys

### ISSUE THREAD

**Issue by jon-butterworth** [confluentinc/terraform-provider-confluentcloud#74]
There doesn't seem to be a way to create the api-keys required for topic creation in an automated fashion? The guide suggests the need for creating the cluster using TF, then manually creating the api-keys on the created cluster, and then adding the keys to TF for another run of TF to create the topics.

This doesn't seem very efficient, and no really in-line with TF's use case. 

Am I missing something?

**Comment by linouk23** [comment]
@jon-butterworth please use `0.7.0` [version](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project) where we introduce `confluent_api_key` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_api_key).
