### ISSUE TITLE
Following the sample docs causes: Error: Could not load plugin

### ISSUE THREAD

**Issue by sionsmith** [confluentinc/terraform-provider-confluentcloud#9]
➜  confluentcloud git:(main) ✗ terraform plan -parallelism=1 -out=tfplan_add_sa_env_and_cluster

```
│ Error: Could not load plugin
│
│
│ Plugin reinitialization required. Please run "terraform init".
│
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│
│ failed to instantiate provider "registry.terraform.io/confluentinc/confluentcloud" to obtain schema: unknown provider
│ "registry.terraform.io/confluentinc/confluentcloud"
```

**Comment by linouk23** [comment]
@sionsmith check out [the docs](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project) for our new `0.2.0` version where we [fixed](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md) that documentation bug.
![image](https://user-images.githubusercontent.com/5459870/140556636-12e6ce36-a160-4faf-a92d-7c53cf7dbb6b.png), thank you for catching the issue!
